In [5]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
         [1.2, 104.2, 52.2, 8.0],
         [1.8, 135.0, 99.0, 0.9],
         ])
print((A))

[[ 56.    0.    4.4  68. ]
 [  1.2 104.2  52.2   8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
calories  = A.sum(axis=0)
print(calories)

[ 59.  239.2 155.6  76.9]


In [10]:
percentage_calories = 100*(A/calories.reshape(1,4))

print(percentage_calories)

[[94.91525424  0.          2.8277635  88.42652796]
 [ 2.03389831 43.56187291 33.54755784 10.40312094]
 [ 3.05084746 56.43812709 63.62467866  1.17035111]]
